Navbar Updated
aiman99aleryany/pancakeswap_V1.0.0 pull request #29
Opened 2022-09-27 15:18 UTC by aryakrm

Navbar Updated

2022-10-01 20:34 UTC, aiman99aleryany requested changes
there are few notes between the codes, make sure to check them.
And change these things:
1- Make less nesting, only 2 layers
2- use "rem" not px, or use the function "toRem(16px)"
3- media queries should be in a separate file as we discussed last time

other than that everything looks good.

2022-10-01 20:34 UTC, aiman99aleryany commented on index.html
> +So great and useful meeting, Thank you so much Carlo for sharing your experience
what is this? haha

2022-10-01 20:34 UTC, aiman99aleryany commented on styles/section1/_section1.scss
> -  background-color: root.$first_background_color;
This is the background color of the section, why did you change it?

2022-10-02 08:12 UTC, aryakrm commented on index.html
> +So great and useful meeting, Thank you so much Carlo for sharing your experience
Hahahahahahah I was writing my messages in meeting in vscode then copy it in meeting chat 😂😂😂 And I forgot to delete the last message 😂😂 I'll delete it

2022-10-02 08:13 UTC, aryakrm commented on styles/section1/_section1.scss
> -  background-color: root.$first_background_color;
Yes because the default variable color is different with the main one you can check it.

2022-10-02 12:25 UTC, aiman99aleryany commented on index.html
> +So great and useful meeting, Thank you so much Carlo for sharing your experience
HAHAHA

2022-10-02 12:26 UTC, aiman99aleryany commented on styles/section1/_section1.scss
> -  background-color: root.$first_background_color;
Ok, I see

2022-10-02 12:30 UTC, aiman99aleryany requested changes
- move the keyframes from section2-wrapper.scss to the animation/animation.scss , and use the keyframes only once, I saw that you are writing the code again.

2022-10-05 10:34 UTC, aiman99aleryany approved these changes

2022-10-05 10:34 UTC, merged