scrollbar
aiman99aleryany/pancakeswap_V1.0.0 pull request #6
Opened 2022-09-11 12:46 UTC by swisscodes

2022-09-11 23:16 UTC, aiman99aleryany requested changes

2022-09-11 23:16 UTC, aiman99aleryany commented on styles/atomic/_scrollbar.scss
> +@use '../atomic/root/root' as *;
@use "./root/root" as *;

2022-09-12 06:32 UTC, swisscodes commented
Wait this merge is blocked because i didnt @use "./root/root" as *;  🗡️ 
please do that while you merge, 

Thank you.

2022-09-13 15:41 UTC, aiman99aleryany approved these changes

2022-09-13 15:41 UTC, merged